### ISSUE TITLE
Video links?

### ISSUE THREAD

**Issue by cecilphillip** [reaqtive/community-presentations#1]
Should we include a links to video interviews and presentations from the team here?
@HowardvanRooijen

**Comment by HowardvanRooijen** [comment]
I've already added it to https://reaqtive.net/talks/ this repo was more to contain decks & demos that people could reuse... But happy to add links here too! Discoverability FTW!

**Comment by cecilphillip** [comment]
I think that would be a good idea to have all those assets in one place for folks
